site_name: Gao's Homepage
site_url: https://gaohomepage.github.io
theme:
  name: material
  features:
    - login:
      username: admin
      password: admin
# nav:
# - Home: index.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js